### ISSUE TITLE
ImportError: No module named weave

### ISSUE THREAD

**Issue by FilipDominec** [FilipDominec/python-meep-install#13]
On Ubuntu 18.04 and Fedora 28, I observed that the installation finishes correctly, but I cannot use meep. This seems independent of multiprocessing options. 

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/meep_mpi.py", line 5988, in <module>
        import scipy.weave
    ImportError: No module named weave

**Comment by mfaulhab** [comment]
worked for me: forcing a scipy version before 0.19 
(_pip install scipy==0.18.1_)
